### PR TITLE
Added Python 3.6 support

### LINKED ISSUE #318: Add Python 3.6 support
'nuff said

### PR DESCRIPTION
**Pull request by brunobord**
## Review

This PR closes #318

* [x] Tests
* [x] Docs/comments (Readme)
* [x] Added the classifier in the setup.py
* [x] `CHANGELOG.rst` Updated
* [ ] Delete your branch

### CODE REVIEW

**Comment by syldlb** [comment]
I'm getting the following error for py36 when using tox : 
`Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named '_sqlite3'`

@alexdashkov have you tried to launch it ?

**Comment by alexdashkov** [comment]
@syldlb nope. Really I have another error. But in your case, it seems that you didn't build all the dependencies

**Comment by brunobord** [comment]
@syldb & @alexdashkov I'm a bit puzzled... could you give me a bit more information in these errors? it works locally, using Python binaries from the famous "deadsnakes" PPA.

**Comment by alexdashkov** [comment]
@brunobord I'm sorry for the miss understanding. For me, it's a local problem and I think it's because I use `pyenv` package. I saw the problem as @syldlb has. It happens when you install a `lite` version of python without all the dependencies (sqlite in his case). 

And about the merge, I want to merge it because I can't run the tests in another PR without your changes.

**Comment by brunobord** [comment]
ok, so... you're just one click away from my merge, if you approve it ;o)

**Pull request merged**
