### PR TITLE
Add an encoding to the open file function to support tests on mac os …

### PR DESCRIPTION
**Pull request by alexdashkov**
## Review

This PR fix problem with the encoding when you run tests on mac. 

* [x] Tests
* [ ] Delete your branch

### CODE REVIEW

**Comment by syldlb** [comment]
I encountered a similar issue on PeopleAsk, and the problem was coming from my system. Are you sure your encoding is properly confirugred? (you can check by typing "locale")

**Comment by alexdashkov** [comment]
@syldlb 
There is a list with locales:
```
locale -a | grep "_FR\|_US"
en_US.US-ASCII
en_US.UTF-8
en_US
fr_FR.ISO8859-1
en_US.ISO8859-15
en_US.ISO8859-1
fr_FR.ISO8859-15
fr_FR.UTF-8
fr_FR
```

**Comment by alexdashkov** [comment]
@brunobord Done!

**Comment by brunobord** [comment]
I think you can safely squash the two commits into one :o)

**Comment by brunobord** [comment]
I've tested on my MacBook Air and I didn't stumble upon any issue without your patch... but there was no trouble with your patch either on my Ubuntu laptop... :/

**Comment by alexdashkov** [comment]
after the investigation of this issue with @wo0dyn, we found a problem. I close this PR.

**Pull request closed without merging**
